image: openjdk:11-jdk

stages:
  - compile
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

compile:
  stage: compile
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test --info
